#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab.
title: "vllur"

# Site description in search engine.
description: ""

# Language settings for html and seo
lang: "en_GB"
iso-lang: "en"

# Production url.
url: "https://vllur.github.io/blog"

# Part after .com, etc. use / if none.
baseurl: /blog/

# Set to true to enable js MathJax
mathjax: false


#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Posts, drafts and other collections in '_content' directory
collections_dir: content

# Projects collection
collections:
  img:
    output: true
    permalink: /:collection/:name

# Appears in header.
author: "vllur"

# Links.
portfolio: "https://vllur.github.io"
github: "https://github.com/vllur"
mastodon: "https://fosstodon.org/@vllur"
linkedin: "https://www.linkedin.com/in/patryk-dejewski"


#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Takes files from root folder, generates site into ./_site.
source: .
destination: ./_site

# Default variables for pages. Are in use if not overwritten.
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



# Excluding dev gem builds from website.
exclude: [vendor]

# Jekyll plugins.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-feed
